CREATE TABLE CORRETORA (
CORRETORA_ID INTEGER PRIMARY KEY IDENTITY(1,1),
NOME VARCHAR(10),
ATUACAO VARCHAR(10)
);

CREATE TABLE ENDERECO (
ENDERECO_ID INTEGER PRIMARY KEY IDENTITY(1,1),
CORRETORA_ID INTEGER,
LOGRADOURO VARCHAR(50),
RUA VARCHAR(50),
NUMERO INTEGER,
BAIRRO VARCHAR(20),
CEP VARCHAR(10),
CIDADE VARCHAR(10),
UF VARCHAR(2),
FOREIGN KEY(CORRETORA_ID) REFERENCES CORRETORA (CORRETORA_ID)
);

CREATE TABLE USUARIO (
USUARIO_ID INTEGER PRIMARY KEY IDENTITY(1,1),
ENDERECO_ID INTEGER,
CORRETORA_ID INTEGER,
NOME VARCHAR(20),
NOME_MEIO VARCHAR(20),
SOBRENOME VARCHAR(20),
DATA_NASCIMENTO DATETIME,
FOREIGN KEY(CORRETORA_ID) REFERENCES CORRETORA (CORRETORA_ID),
FOREIGN KEY(ENDERECO_ID) REFERENCES ENDERECO (ENDERECO_ID)
);

CREATE TABLE TELEFONE (
TELEFONE_ID INTEGER PRIMARY KEY IDENTITY(1,1),
USUARIO_ID INTEGER,
CORRETORA_ID INTEGER,
TIPO VARCHAR(10),
DDD INTEGER,
NUMERO INTEGER,
FOREIGN KEY(CORRETORA_ID) REFERENCES CORRETORA (CORRETORA_ID),
FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO (USUARIO_ID)
);